stages:
  data_ingestion:
    cmd: python src/malaria_cnn/pipeline/data_ingestion_pipeline.py
    deps:
    - src/malaria_cnn/pipeline/data_ingestion_pipeline.py
    - config/config.yaml
    outs:
    - artifacts/data_ingestion/cell-images-for-detecting-malaria