stages:
  data_ingestion:
    cmd: python src/malaria_cnn/pipeline/data_ingestion_pipeline.py
    deps:
    - src/malaria_cnn/pipeline/data_ingestion_pipeline.py
    - config/config.yaml
    outs:
    - artifacts/data_ingestion/cell_images
  
  prepare_base_model:
    cmd: python src/malaria_cnn/pipeline/base_model_pipeline.py
    deps:
    - src/malaria_cnn/pipeline/base_model_pipeline.py
    - config/config.yaml
    - params.yaml
    outs:
    -  artifacts/prepare_base_model/base_model.h5
    -  artifacts/prepare_base_model/base_model_updated.h5

  training_base_model:
   cmd: python src/malaria_cnn/pipeline/training_base_model_pipeline.
   deps:
    - src/malaria_cnn/pipeline/training_base_model_pipeline.py
    - config/config.yaml
    - params.yaml
    - artifacts/prepare_base_model/base_model.h5